(defclass dialog-input () ((update-plist :initarg update-plist :accessor update-plist)))
	(defclass message-input (dialog-input) ())
		(defclass command-input (message-input) 
			((name :initarg name :accessor command-name) 
			 (text :initarg text)))
		(defclass text-input (message-input) ())
	(defclass callback-input (dialog-input) ())
		(defclass callback-button-input (callback-input) 
			((data :initarg data :accessor callback-data)))