(pushnew (uiop:getcwd) ql:*local-project-directories*)
(ql:quickload '(:jonathan :drakma))
(asdf:load-asd "telegram-bot-api.asd")
(ql:quickload :telegram-bot-api)
(in-package :telegram-bot-api)
(main)