(in-package :api-response)

(defclass chat (has-raw-plist)
	(;(message-object :initform message-object)
	 (id :accessor id :initarg id)
	 (chat-type :accessor chat-type :initarg chat-type)
	 (title :accessor title :initarg title)
	 (username :accessor username :initarg username)
	 (first_name :accessor first_name :initarg first_name)
	 (last_name :accessor last_name :initarg last_name)
	 (is_forum :accessor is_forum :initarg is_forum)))